# Travel RAG System Configuration
# This file contains all configuration settings for the travel recommendation RAG pipeline

# Database Configuration
database:
  # PostgreSQL settings for storing conversations and feedback
  postgres:
    host: "localhost"
    port: 5432
    database: "brahman"
    username: "admin"
    password: "admin"
    
  # Elasticsearch settings for vector search
  elasticsearch:
    host: "localhost"
    port: 9200
    index_name: "travel_docs"
    timeout: 30

# Embedding Model Configuration
embedding:
  # Hugging Face model for generating document embeddings
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  model_dimension: 384
  batch_size: 32
  device: "cpu"  # Change to "cuda" if you have GPU
  
  # Alternative embedding models (uncomment to use)
  # model_name: "BAAI/bge-large-en-v1.5"
  # model_dimension: 1024

# Large Language Model Configuration
llm:
  # Open AI settings
  provider: "openai"
  model_name: "gpt-3.5-turbo"  
  temperature: 0.3


# Document Processing Configuration
document_processing:
  # PDF processing settings
  chunk_size: 500
  chunk_overlap: 100
  
  # Supported file formats
  supported_formats: ["pdf", "txt", "md"]
  
  # Output directories
  input_directory: "data/raw"
  processed_directory: "data/processed"
  embeddings_directory: "data/embeddings"

# RAG System Settings
rag:
  # Retrieval settings
  top_k_documents: 5
  similarity_threshold: 0.7
  hybrid_search: true
  
  # Response generation settings
  include_sources: true
  max_context_length: 3000

# Travel Domain Specific Settings
travel:
  # Supported regions/countries for recommendations
  supported_region:
    - "India"
  
  # Travel categories for better organization
  categories:
    - "accommodations"
    - "attractions"
    - "transportation"
    - "food_dining"
    - "cultural_experiences"
    - "sustainable_tourism"

# Monitoring and Logging
monitoring:
  # Grafana dashboard settings
  grafana_port: 3000
  
  # Logging configuration
  log_level: "INFO"
  log_file: "logs/travel_rag.log"
  
  # Performance metrics to track
  metrics:
    - "response_time"
    - "retrieval_accuracy" 
    - "user_satisfaction"
    - "system_uptime"

# Security Settings
security:
  # API rate limiting
  rate_limit:
    requests_per_minute: 60
    requests_per_hour: 1000
  
  # Data privacy
  anonymize_user_data: true
  data_retention_days: 90

# Development/Production Settings
environment:
  # Set to 'development' or 'production'
  mode: "development"
  
  # Debug settings
  debug: true
  verbose_logging: true
  
  # Cache settings
  enable_cache: true
  cache_ttl: 3600  # 1 hour in seconds