version: '3.8'

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "${QDRANT_PORT:-6333}:6333"
      - "${QDRANT_GRPC_PORT:-6334}:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334

  # Ollama for local LLM models
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"

  # PostgreSQL Database
  postgres:
    image: postgres:13
    container_name: postgres-rag
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-brahman}
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Streamlit Application - FIXED CONFIGURATION
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit
    environment:
      # Fixed database credentials to match postgres service
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB:-brahman}
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - POSTGRES_PORT=5432
      # Other services
      - QDRANT_URL=http://qdrant:${QDRANT_PORT:-6333}
      - OLLAMA_URL=http://ollama:${OLLAMA_PORT:-11434}/v1/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
    ports:
      - "${STREAMLIT_PORT:-8501}:8501"
    depends_on:
      - qdrant
      - ollama
      - postgres
    # Remove volume mount since we're copying files in Dockerfile
    # volumes:
    #   - .:/app

  # PgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  # Grafana for Monitoring
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    depends_on:
      - postgres

volumes:
  postgres_data:
  grafana_data:
  qdrant_storage:
  ollama_data:
