version: '3.8'

services:
  # Qdrant Vector Database (replaces Elasticsearch)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "${QDRANT_PORT:-6333}:6333"
      - "${QDRANT_GRPC_PORT:-6334}:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT_URL=http://qdrant:${QDRANT_PORT:-6333}
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334

  # Ollama for local LLM models
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    environment:
      - OLLAMA_URL=http://ollama:${OLLAMA_PORT:-11434}/v1/

  # OpenAI 
  OpenAI:
    image: openai/openai
    container_name: openai
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "${OPENAI_PORT:-5000}:5000"



  # PostgreSQL Database
  postgres:
    image: postgres:13
    container_name: postgres-rag
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB:-brahman}                    
      - POSTGRES_USER=${POSTGRES_USER:-admin}                  
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin} 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:

  # Streamlit Application
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit
    environment:
      - QDRANT_URL=http://qdrant:${QDRANT_PORT:-6333}
      - OLLAMA_URL=http://ollama:${OLLAMA_PORT:-11434}/v1/
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB:-rag_assistant}
      - POSTGRES_USER=${POSTGRES_USER:-rag_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-rag_password}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
    ports:
      - "${STREAMLIT_PORT:-8501}:8501"
    depends_on:
      - qdrant
      - ollama
      - postgres
    volumes:
      - .:/app

  # Grafana for Monitoring
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    depends_on:
      - postgres